# Generated by Django 6.0.4 on 2026-06-26 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('codigo_fifa', models.CharField(max_length=3, unique=True)),
                ('grupo', models.CharField(choices=[('Grupo A', 'Grupo A'), ('Grupo B', 'Grupo B'), ('Grupo C', 'Grupo C'), ('Grupo D', 'Grupo D'), ('Grupo E', 'Grupo E'), ('Grupo F', 'Grupo F'), ('Grupo G', 'Grupo G'), ('Grupo H', 'Grupo H'), ('Grupo I', 'Grupo I'), ('Grupo J', 'Grupo J'), ('Grupo K', 'Grupo K'), ('Grupo L', 'Grupo L'), ('Grupo M', 'Grupo M'), ('Grupo N', 'Grupo N'), ('Grupo O', 'Grupo O'), ('Grupo P', 'Grupo P')], max_length=10)),
                ('entrenador', models.CharField(max_length=100)),
                ('bandera', models.ImageField(blank=True, null=True, upload_to='banderas/')),
            ],
            options={
                'ordering': ['grupo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Estadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('capacidad', models.PositiveIntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='estadios/')),
            ],
            options={
                'verbose_name_plural': 'Estadios',
                'ordering': ['pais', 'ciudad'],
            },
        ),
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('principal', 'Principal'), ('entrenamiento', 'Entrenamiento'), ('calentamiento', 'Calentamiento')], default='principal', max_length=20)),
                ('superficie', models.CharField(choices=[('cesped_natural', 'Césped Natural'), ('cesped_sintetico', 'Césped Sintético'), ('tierra', 'Tierra')], max_length=20)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('mantenimiento', 'En Mantenimiento')], default='disponible', max_length=20)),
                ('largo', models.DecimalField(decimal_places=2, help_text='En metros', max_digits=5)),
                ('ancho', models.DecimalField(decimal_places=2, help_text='En metros', max_digits=5)),
                ('estadio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canchas', to='Api.estadio')),
            ],
            options={
                'ordering': ['estadio', 'numero'],
                'unique_together': {('estadio', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('fase', models.CharField(choices=[('grupos', 'Fase de Grupos'), ('octavos', 'Octavos de Final'), ('cuartos', 'Cuartos de Final'), ('semifinal', 'Semifinal'), ('tercer_puesto', 'Tercer Puesto'), ('final', 'Final')], max_length=20)),
                ('arbitro', models.CharField(blank=True, max_length=100)),
                ('goles_local', models.PositiveIntegerField(blank=True, null=True)),
                ('goles_visitante', models.PositiveIntegerField(blank=True, null=True)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidos', to='Api.cancha')),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidos_local', to='Api.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidos_visitante', to='Api.equipo')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('duracion_horas', models.PositiveIntegerField(default=2)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=15)),
                ('motivo', models.TextField(blank=True, help_text='Ej: Entrenamiento pre-partido')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='Api.cancha')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='Api.equipo')),
            ],
            options={
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('numero_camiseta', models.PositiveIntegerField()),
                ('posicion', models.CharField(choices=[('POR', 'Portero'), ('DEF', 'Defensa'), ('MED', 'Mediocampista'), ('DEL', 'Delantero')], max_length=3)),
                ('fecha_nacimiento', models.DateField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='Api.equipo')),
            ],
            options={
                'ordering': ['equipo', 'numero_camiseta'],
                'unique_together': {('equipo', 'numero_camiseta')},
            },
        ),
    ]
