# Generated by Django 6.0.4 on 2026-07-03 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_estadio_latitud_estadio_longitud'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partido',
            name='cancha',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='cancha',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='equipo',
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AddField(
            model_name='partido',
            name='descripcion',
            field=models.CharField(blank=True, help_text='Ej: Ganador Grupo A vs Segundo Grupo B', max_length=200),
        ),
        migrations.AddField(
            model_name='partido',
            name='entradas_disponibles',
            field=models.PositiveIntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='partido',
            name='estadio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='partidos', to='Api.estadio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partido',
            name='precio_general',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='partido',
            name='precio_platea',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='partido',
            name='precio_vip',
            field=models.DecimalField(decimal_places=2, default=300.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='partido',
            name='equipo_local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partidos_local', to='Api.equipo'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='equipo_visitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partidos_visitante', to='Api.equipo'),
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('general', 'General'), ('platea', 'Platea'), ('vip', 'VIP')], default='general', max_length=10)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('precio_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='confirmada', max_length=10)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('codigo', models.CharField(blank=True, max_length=20, unique=True)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='Api.partido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Entradas',
                'ordering': ['-fecha_compra'],
            },
        ),
        migrations.DeleteModel(
            name='Cancha',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
