# Generated by Django 6.0.4 on 2026-07-07 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_remove_partido_cancha_remove_reserva_cancha_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partido',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterField(
            model_name='partido',
            name='fase',
            field=models.CharField(choices=[('grupos', 'Fase de Grupos'), ('dieciseisavos', 'Ronda de 32'), ('octavos', 'Octavos de Final'), ('cuartos', 'Cuartos de Final'), ('semifinal', 'Semifinal'), ('tercer_puesto', 'Tercer Puesto'), ('final', 'Final')], max_length=20),
        ),
    ]
